#!/bin/bash
set -e
cd "$(dirname "$0")"
g++ -c -nodefaultlibs -fno-rtti -fno-exceptions -lc stdlib.cpp -o stdlib.o
(
echo '// <auto-generated />
namespace KJU.Application
{
    using System;

    public static class BundledStdlib {
          public static byte[] data = Convert.FromBase64String(@"'
base64 < stdlib.o
echo '");
     }
}'
) > ../KJU.Application/BundledStdlib.cs
