#!/bin/bash
set -e
cd "$(dirname "$0")"

# -fno-omit-frame-pointer -- do not use RBP as a general-purpose register
# -masm=intel -- use sane Intel assembly syntax (instead of AT&T).
# -static -- do NOT use dynamic linking

g++ -c -static -std=c++14 -fno-omit-frame-pointer -g -masm=intel -nodefaultlibs -fno-rtti -fno-exceptions -lc++ stdlib.cpp -o stdlib.o
(
echo '// <auto-generated />
namespace KJU.Application
{
    using System;

    public static class BundledStdlib {
          public static byte[] data = Convert.FromBase64String(@"'
base64 < stdlib.o
echo '");
     }
}'
) > ../KJU.Application/BundledStdlib.cs
